import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

/** Visible label on every piece of AI output. */
export function AiBadge({ model, className }: { model?: string; className?: string }) {
  return (
    <span
      className={cn(
        "border-line-purple/50 bg-line-purple/10 text-line-purple inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-semibold tracking-wide uppercase",
        className,
      )}
      title={model ? `Generated by ${model}` : "Generated by a language model"}
    >
      <Sparkles className="size-3" aria-hidden />
      AI-generated
      {model && (
        <span className="font-mono font-normal tracking-normal normal-case opacity-80">· {model}</span>
      )}
    </span>
  );
}
